### ISSUE TITLE
[Agent] Multi-Agent Runner

### ISSUE THREAD

**Issue by chr-hertel** [symfony/ai#19]
Currently the agent is only a slim wrapper around the Platform and basically only has a few features
* structured output (should that be in Platform?)
* input/output extension points (should that be in Platform?)
* validation of input & capabilities (should that be in Platform?)
* handling of multi-step tool calling <- the only feature atm?

One big feature we should enable is multi-agent with different characteristics:
1. orchestration agent
  one agent that is the main agent and basically uses other agents as tools (should be possible already)
2. agent hand-off
  multiple agents handing off the responsibility and context between each other

**Comment by CashWilliams** [comment]
I'd love to see a2a support for the agent built in.

**Comment by junaidbinfarooq** [comment]
@chr-hertel @OskarStark 
I would like to work on this one. Do you have any particular idea on its implementation? Following is a rough sketch of how it would work IMO.

The multi-agent system operates in a sequential handoff pattern where specialized agents collaborate to complete complex tasks:
### Setup Phase
**Agent Definition:** Each agent is created with specific capabilities (research, writing, review)
**System Prompts:** Agents are given specialized instructions and told when to hand off
**Handoff Rules:** The system creates rules for when agents should transfer control

### Execution Flow
`User Request → Orchestrator/Initial Agent → Specialized Agent 1 → Agent 2 → Agent 3 → Final Result`

### Two Execution Patterns
**Pattern A: Orchestrated Workflow**
An orchestrator agent receives the user request
It coordinates and delegates to specialized agents
Each agent completes its part and suggests the next handoff

**Pattern B: Direct Collaboration**
Agents work directly with each other without a central orchestrator
Each agent analyzes the conversation and decides when to hand off

### Handoff Triggers
The system detects handoffs through:
**Explicit mentions:** Agent says "handoff to writer" or "transfer to reviewer"
**Capability detection:** Agent mentions capabilities it doesn't have
**Automatic rules:** Pre-configured rules based on agent capabilities

This creates a collaborative pipeline where each agent contributes its expertise, resulting in higher-quality outputs than a single general-purpose agent could produce.

Let me know your thoughts.

**Comment by OskarStark** [comment]
I don't have any concrete plans yet and Chris is off for some days. So maybe give it a try and draft a PR with a working example?

**Comment by junaidbinfarooq** [comment]
> [@chr-hertel](https://github.com/chr-hertel) [@OskarStark](https://github.com/OskarStark) I would like to work on this one. Do you have any particular idea on its implementation? Following is a rough sketch of how it would work IMO.
> 
> The multi-agent system operates in a sequential handoff pattern where specialized agents collaborate to complete complex tasks:
> 
> ### Setup Phase
> **Agent Definition:** Each agent is created with specific capabilities (research, writing, review) **System Prompts:** Agents are given specialized instructions and told when to hand off **Handoff Rules:** The system creates rules for when agents should transfer control
> 
> ### Execution Flow
> `User Request → Orchestrator/Initial Agent → Specialized Agent 1 → Agent 2 → Agent 3 → Final Result`
> 
> ### Two Execution Patterns
> **Pattern A: Orchestrated Workflow** An orchestrator agent receives the user request It coordinates and delegates to specialized agents Each agent completes its part and suggests the next handoff
> 
> **Pattern B: Direct Collaboration** Agents work directly with each other without a central orchestrator Each agent analyzes the conversation and decides when to hand off
> 
> ### Handoff Triggers
> The system detects handoffs through: **Explicit mentions:** Agent says "handoff to writer" or "transfer to reviewer" **Capability detection:** Agent mentions capabilities it doesn't have **Automatic rules:** Pre-configured rules based on agent capabilities
> 
> This creates a collaborative pipeline where each agent contributes its expertise, resulting in higher-quality outputs than a single general-purpose agent could produce.
> 
> Let me know your thoughts.

@chr-hertel @OskarStark 
I have a rough implementation of this locally.
Please let me know your thoughts on this before I proceed further.

**Comment by OskarStark** [comment]
If you have something, can you create a PR? Its easier to discuss about code 😄

**Comment by chr-hertel** [comment]
Yea, maybe start with some concrete examples - maybe inspired by what [langgraph](https://langchain-ai.github.io/langgraph/concepts/multi_agent/), [autogen](https://github.com/microsoft/autogen), [semantic-kernel](https://github.com/microsoft/semantic-kernel), or others have.

**Comment by OskarStark** [comment]
For a concrete use case, I could imagine sth. like:

> We want to have an agent who is the orchestrator and receives the request by the user. the task is that this orchestrator should decide if the question is a general question, in this case he should answer on its own, if it is a technical support question or if it is a marketing/sales/info question regarding a fiction product. lets imagine we are owner of a Saas product. in this case the orchestrator should handoff the question to another configured agent, who should answer the question and return it to the User.

```mermaid
flowchart TD
    A[User Query] --> B[Orchestrator Agent]
    B --> C{Query Classification}
    
    C -->|Technical Support| D[Technical Agent]
    C -->|Marketing/Sales| E[Sales Agent]
    C -->|General/Other| B
    
    B --> F[Orchestrator Handles Directly]
    D --> G[Response to User]
    E --> G
    F --> G
    
    style A fill:#e1f5fe
    style B fill:#f3e5f5
    style D fill:#fff3e0
    style E fill:#fce4ec
    style F fill:#e8f5e8
    style G fill:#e1f5fe
```

### Dummy code
```php
<?php

use Symfony\AI\Agent\Agent;
use Symfony\AI\Agent\MultiAgent;
use Symfony\AI\Agent\AgentClassification;
use Symfony\AI\Agent\RoutingDecision;
use Symfony\AI\Agent\InputProcessor\SystemPromptInputProcessor;
use Symfony\AI\Agent\StructuredOutput\StructuredOutputProcessor;
use Symfony\AI\Agent\StructuredOutput\ResponseFormatFactory;

// 1. Create and configure the orchestrator agent
$orchestratorPrompt = new SystemPromptInputProcessor(
    'You are an intelligent query classifier. Analyze user queries and classify them into one of these categories: ' .
    implode(', ', array_map(fn($case) => $case->value, AgentClassification::cases())) . '. ' .
    'Return a JSON object with: target (the classification), confidence (0-1), and reasoning (explanation).'
);

$responseFormat = ResponseFormatFactory::fromClass(RoutingDecision::class);
$structuredProcessor = new StructuredOutputProcessor($responseFormat);

$orchestrator = new Agent(
    $platform,
    $model,
    [$orchestratorPrompt, $structuredProcessor],
    [$structuredProcessor]
);

// 2. Create specialized agents
$technicalAgent = new Agent($platform, $model, [
    new SystemPromptInputProcessor(
        'You are a technical support specialist. Help with bugs, errors, and technical issues.'
    )
]);

$salesAgent = new Agent($platform, $model, [
    new SystemPromptInputProcessor(
        'You are a sales specialist. Help with pricing, plans, and product features.'
    )
]);

$generalAgent = new Agent($platform, $model, [
    new SystemPromptInputProcessor(
        'You are a helpful assistant. Answer general questions concisely.'
    )
]);

// 3. Create MultiAgent with orchestrator and agents
$multiAgent = new MultiAgent(
    [
        'orchestrator' => $orchestrator,
        'technical' => $technicalAgent,
        'sales' => $salesAgent,
        'general' => $generalAgent,
    ],
    logger()
);

// 4. Use as any AgentInterface
$messages = new MessageBag(Message::ofUser('I\'m getting error 500 when logging in'));
$result = $multiAgent->call($messages);

echo $result->getContent();

// 5. Check execution details
$lastExecution = $multiAgent->getLastExecution();
echo "Handled by: " . $lastExecution['agent']; // 'technical'
```

WDYT?

**Comment by chr-hertel** [comment]
I think for the sake of DX/API I would favor sth like this:
```php
$salesAgent = new Agent(
    name: 'sales',
    platform: $platform,
    model: $model,
    instructions: 'You are a sales specialist. Help with pricing, plans, and product features.'
);
```

**Comment by junaidbinfarooq** [comment]
I had made some code changes locally, but didn't commit them, and now they are gone as far as I can see 🤦‍♂️

**Comment by OskarStark** [comment]
So you want to add the `name` to `AgentInterface` @chr-hertel?

**Comment by chr-hertel** [comment]
It's just that this array here is a bit of a downer:
```php
$multiAgent = new MultiAgent(
    [
        'orchestrator' => $orchestrator,
        'technical' => $technicalAgent,
        'sales' => $salesAgent,
        'general' => $generalAgent,
    ],
    logger()
);
```

I know we could handle that in the bundle quite well, but with the plain component ... naah

On top, it's not the first time that an `AgentInterface::getName()` would help, also with features like #352 for example

**Comment by OskarStark** [comment]
I agree, so let's do it

**Comment by chr-hertel** [comment]
one thing, currently Platform and Agent are suuuper similar.
for example the most examples for platform bridges _use_ the `Agent`, but wouldn't _need_ the agent, since it is single API call, nothing sophisticated. that's something we could clean up then as well, and sort stuff better.

**Comment by OskarStark** [comment]
But I would vote to educate for Agent as the entrypoint, so 🤔

**Comment by OskarStark** [comment]
See 
* #509

**Comment by aszenz** [comment]
> one thing, currently Platform and Agent are suuuper similar. for example the most examples for platform bridges _use_ the `Agent`, but wouldn't _need_ the agent, since it is single API call, nothing sophisticated. that's something we could clean up then as well, and sort stuff better.

I agree, Agent vs Platform distinction is not clear in the docs right now, a lot of AI use cases only need structured output, an agent is not needed. Multi-step dynamic tool call is the only real feature that needs agents.

**Comment by aszenz** [comment]
In light of the above statement a multi-agent runner should be able to delegate tasks to platforms as well and not just agents.

Right now we have created multiple AI Services

1. AI Navigator (generates url's from user queries)
2. AI dashboard (generates dashboard config (structured output) from user queries)
3. AI Form filler (generates form json from user query)

But now we want to have an agentic chat app that can delegate to these platforms based on user input.

Right now there are two ways to do this:

1. Register these services as tools to Chat Agent, so it can call them directly.
2. Turn Chat Agent into an orchestrator for calling these ai platforms

I like option 2) since it allows for using the platforms directly or via an agent.

**Comment by OskarStark** [comment]
* #509

is the first puzzle piece and if I get it right @chr-hertel, you want to add another `?string $instructions = null` parameter to the `Agent` constructor and convert it internally to an input process -> `SystemPromptInputProcessor`?

At least after the `getName()` method, we can simplify the dummy code to:
```diff

use Symfony\AI\Agent\Agent;
use Symfony\AI\Agent\MultiAgent;
use Symfony\AI\Agent\AgentClassification;
use Symfony\AI\Agent\RoutingDecision;
use Symfony\AI\Agent\InputProcessor\SystemPromptInputProcessor;
use Symfony\AI\Agent\StructuredOutput\StructuredOutputProcessor;
use Symfony\AI\Agent\StructuredOutput\ResponseFormatFactory;

// 1. Create and configure the orchestrator agent
$orchestratorPrompt = new SystemPromptInputProcessor(
    'You are an intelligent query classifier. Analyze user queries and classify them into one of these categories: ' .
    implode(', ', array_map(fn($case) => $case->value, AgentClassification::cases())) . '. ' .
    'Return a JSON object with: target (the classification), confidence (0-1), and reasoning (explanation).'
);

$responseFormat = ResponseFormatFactory::fromClass(RoutingDecision::class);
$structuredProcessor = new StructuredOutputProcessor($responseFormat);

$orchestrator = new Agent(
    $platform,
    $model,
    [$orchestratorPrompt, $structuredProcessor],
    [$structuredProcessor],
+   name: 'orchestrator'    
);

// 2. Create specialized agents
-$technicalAgent = new Agent($platform, $model, [
+$technicalAgent = new Agent($platform, $model, name: 'technical', inputProcessors: [
    new SystemPromptInputProcessor(
        'You are a technical support specialist. Help with bugs, errors, and technical issues.'
    )
]);

-$salesAgent = new Agent($platform, $model, [
+$salesAgent = new Agent($platform, $model, name: 'sales', inputProcessors: [
    new SystemPromptInputProcessor(
        'You are a sales specialist. Help with pricing, plans, and product features.'
    )
]);

-$generalAgent = new Agent($platform, $model, [
+$generalAgent = new Agent($platform, $model, name: 'sales', inputProcessors: [
    new SystemPromptInputProcessor(
        'You are a helpful assistant. Answer general questions concisely.'
    )
]);

// 3. Create MultiAgent with orchestrator and agents
$multiAgent = new MultiAgent(
    [
-        'orchestrator' => $orchestrator,
-        'technical' => $technicalAgent,
-        'sales' => $salesAgent,
-        'general' => $generalAgent,
+        $orchestrator,
+        $technicalAgent,
+        $salesAgent,
+        $generalAgent,
    ],
    logger()
);

// 4. Use as any AgentInterface
$messages = new MessageBag(Message::ofUser('I\'m getting error 500 when logging in'));
$result = $multiAgent->call($messages);

echo $result->getContent();

// 5. Check execution details
$lastExecution = $multiAgent->getLastExecution();
echo "Handled by: " . $lastExecution['agent']; // 'technical'
```

Despite the instructions (which is just aDX thing for now), still missing how we define the "strategy" internally for who answers what.

From the bundle POV it could look like:
```yaml
# config/packages/ai.yaml
ai:
    platform:
        openai:
            api_key: '%env(OPENAI_API_KEY)%'
    
    agent:
        general:
            model: 'gpt-4o-mini'
            system_prompt: 'You are a general assistant.'
        
        sales:
            model: 'gpt-4o-mini'
            system_prompt: 'You are a sales specialist.'
        
        technical:
            model: 'gpt-4o'
            system_prompt: 'You are a technical specialist.'
        
        orchestrator:
            model: 'gpt-4o'
            system_prompt: 'You orchestrate a team of agents.'
    
    multi_agent:
        inbound_question:
            strategy: 'orchestrated'
            agents:
                - 'ai.agent.orchestrator'
                - 'ai.agent.general'
                - 'ai.agent.sales'  
                - 'ai.agent.technical'
            
            # Define when and how handoffs occur
            handoff:
                rules:
                    - prompt: 'If the question or conversation is about pricing, costs, plans, or subscriptions'
                      target: 'ai.agent.sales'
                    - prompt: 'If the question involves bugs, errors, implementation details, or API usage'
                      target: 'ai.agent.technical'
                    - prompt: 'For general questions or when unsure'
                      target: 'ai.agent.general'
                
                # Instructions for orchestrator delegation (structured output)
                delegation_prompt: |
                    Analyze the query and decide which agent to delegate to.
                    Return: {"delegate_to": "agent_id"}
```

I ignored complexity like `max_iterations` etc. for now to keep it simple. We could also think about using a `pattern` instead of the `prompt` if the delegation should be based on preg_match and not an LLM.
